packages: []
allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalogs:
  build:
    tsdown: ^0.22.14
    unbuild: ^3.6.1
  dev:
    bumpp: ^12.2.0
    pncat: ^0.13.2
    simple-git-hooks: ^2.13.1
    taze: ^20.0.0
    tsx: ^4.23.11
    typescript: ^6.0.3
  lint:
    '@octohash/eslint-config': ^0.5.3
    eslint: ^10.8.1
    lint-staged: ^17.3.0
  prod:
    ansis: ^4.3.1
    cac: ^7.0.0
    execa: ^10.0.1
    p-retry: ^8.0.0
    pathe: ^2.0.3
    unconfig: ^7.5.0
    yocto-spinner: ^1.2.2
  test:
    vitest: ^4.1.10
  types:
    '@types/node': ^26.2.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
